name: build
on: push
jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        xcode:
          - 12.4
    env:
      COCOTODON_MRUBY_BUILD_TYPES: release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Select Xcode
        run: sudo xcode-select --switch /Applications/Xcode_${{ matrix.xcode }}.app

      - name: Install tools for build mruby
        run: brew install automake

      - name: Install dependencies
        run: pod install

      - name: Make build directory
        run: mkdir -p build

      - name: Cache mruby build
        uses: actions/cache@v2
        env:
          cache-revision: 1
        with:
          path: ${{ github.workspace }}/mruby/build/
          key: ${{ hashFiles('build_config.rb') }}-${{ hashFiles('.git/modules/mruby/HEAD') }}-${{ matrix.xcode }}-${{ env.cache-revision }}

      - name: Build
        run: xcodebuild -workspace Cocotodon.xcworkspace -scheme Cocotodon clean archive -archivePath build/Cocotodon.xcarchive

      - name: Packaging
        working-directory: build
        run: |
          mkdir -p Cocotodon
          cp -a Cocotodon.xcarchive/Products/Applications/Cocotodon.app Cocotodon/Cocotodon.app
          cp -f ${{ github.workspace }}/README.md Cocotodon/
          cp -f ${{ github.workspace }}/LICENSE Cocotodon/
          zip -r Cocotodon-${{ github.sha }}.zip Cocotodon/

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: build/Cocotodon-${{ github.sha }}.zip
